name: Publish Package

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Add the GitHub NuGet registry password
        run: |
          dotnet nuget update source "GitHub" --username ${{ github.actor }} \
            --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text

      - name: Package the project
        run: dotnet pack -c Release

      - name: Add the GitHub NuGet registry as a package source
        run: |
          dotnet nuget add source --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/inspirational-impala-inc/index.json"

      - name: Publish the package
        run: |
          dotnet nuget push 'bin/Release/*.nupkg' --source "github" \
             --api-key ${{ secrets.GITHUB_TOKEN }}
